site_name: Spark Delta & Iceberg
site_description: >
  Trabalho universitário sobre Delta Lake e Apache Iceberg com Apache Spark (PySpark)
site_author: Gabriel Minatto, Anderson dos Santos, Lorenzo
repo_url: https://github.com/Lorenbou/spark-delta-apache
repo_name: Lorenbou/spark-delta-apache

theme:
  name: material
  language: pt
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy

nav:
  - Início: index.md
  - Apache Spark: spark.md
  - Delta Lake: delta.md
  - Apache Iceberg: iceberg.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - tables
  - attr_list
